setWindingData({
    metaConfig: {
        title: "General Concepts of Rotating Electrical Machine (Part 2)",
        range: "Question Range: 101 to 181",
        hours: 1,
        minutes: 0
    },
    questions: [
{
num:101,
question:"Inter–poles are used in ..........",
options:{
A:"Lap wound machines",
B:"Wave wound machines",
C:"Both lap and wave wound machines",
D:"None of these"
},
answer:"C"
},

{
num:102,
question:"For the production of induced e.m.f field system of an electric machine ................",
options:{
A:"Must be on stator",
B:"May be on stator or rotor",
C:"Must be on rotor",
D:"None of these"
},
answer:"B"
},

{
num:103,
question:"The number of conductors of the compensating winding in a D.C. machine",
options:{
A:"Is always more than the number of armature conductors per pole",
B:"Is always less than the number of armature conductors per pole",
C:"May be less or more than the number of armature conductors per pole",
D:"None of these"
},
answer:"B"
},

{
num:104,
question:"In a D.C. machine, how are the commutating pole winding connected?",
options:{
A:"In series with the shunt winding",
B:"Parallel to the shunt winding",
C:"In series with the armature winding",
D:"Parallel to the armature winding"
},
answer:"C"
},

{
num:105,
question:"In electromechanical energy conversion devices (e.g. generators and motors), a small air gap is left between the stator and rotor in order to .......",
options:{
A:"Reduce the reluctance of the magnetic path",
B:"Increase flux density in the air gap",
C:"Permit mechanical clearance",
D:"Avoid saturation of field"
},
answer:"C"
},

{
num:106,
question:"Magnitude of E.M.F. induced in a circuit is directly proportional to",
options:{
A:"the magnetic flux",
B:"the size of the flux",
C:"rate of change of flux",
D:"None of the above"
},
answer:"C"
},

{
num:107,
question:"What is the condition of retrogressive winding in dc machines?",
options:{
A:"Y<sub>B</sub> > Y<sub>F</sub>",
B:"Y<sub>B</sub> < Y<sub>F</sub>",
C:"Y<sub>B</sub> = Y<sub>F</sub>",
D:"Y<sub>B</sub> + Y<sub>F</sub> = 0"
},
answer:"B"
},

{
num:108,
question:"The emf generated in dc generator depends upon............",
options:{
A:"Brush contact drop",
B:"Number of parallel path",
C:"Terminal voltage",
D:"Commutation"
},
answer:"B"
},

{
num:109,
question:"Which part of the electrical machine provided mechanical support to the poles and path for magnetic flux?",
options:{
A:"Armature conductor",
B:"Brushes",
C:"Field winding",
D:"Yoke"
},
answer:"D"
},

{
num:110,
question:"Armature coil of a DC machine is usually made up of :",
options:{
A:"mica",
B:"copper",
C:"brass",
D:"graphite"
},
answer:"B"
},

{
num:111,
question:"The generator which gives DC supply to the rotor is called :",
options:{
A:"Converter",
B:"Exciter",
C:"Inverter",
D:"Rectifier"
},
answer:"B"
},

{
num:112,
question:"Frequency of electromotive force, generated by generator depend upon",
options:{
A:"Motion",
B:"Number of poles",
C:"(a) and (b) both",
D:"None of the above"
},
answer:"C"
},

{
num:113,
question:"In starting DC generator provides-",
options:{
A:"A.C.",
B:"D.C.",
C:"(A.C.) and (D.C.) both",
D:"None"
},
answer:"A"
},
 
{
num:114,
question:"The yoke of small DC machine is made up of–",
options:{
A:"Cast iron",
B:"Aluminium",
C:"Stainless steel",
D:"Copper"
},
answer:"A"
},

{
num:115,
question:"The field of self-excited generator is excited by–",
options:{
A:"AC",
B:"DC",
C:"By its own current",
D:"Either AC or DC"
},
answer:"C"
},

{
num:116,
question:"Fleming's right hand rule is used for the determination of direction of :",
options:{
A:"Force acting on a current carrying conductor kept in a magnetic field",
B:"Motion of a current carrying conductor kept in an electric field",
C:"Current induced in a conductor due to its motion in a magnetic field",
D:"Deflection of a charged particle moving in a magnetic field"
},
answer:"C"
},

{
num:117,
question:"In a DC machine, each conductor lies at ________ to the magnetic flux and in the direction of its movement.",
options:{
A:"180°",
B:"120°",
C:"0°",
D:"90°"
},
answer:"D"
},

{
num:118,
question:"The best way to produce reversing voltage to neutralise the reactance voltage is by using:",
options:{
A:"compensating winding",
B:"carbon brushes",
C:"equaliser rings",
D:"interpoles"
},
answer:"D"
},

{
num:119,
question:"The reversal of current in a coil as the coil passes the brush axis is called:",
options:{
A:"generator action",
B:"motoring action",
C:"armature reaction",
D:"commutation"
},
answer:"D"
},

{
num:120,
question:"______ is a hetero-polar structure with stationary poles and a rotating armature.",
options:{
A:"A three-phase synchronous motor",
B:"A single-phase induction motor",
C:"A three-phase induction motor",
D:"A DC machine"
},
answer:"D"
},

{
num:121,
question:"The commutator segments are connected to the armature conductors by means of",
options:{
A:"Copper lugs",
B:"Resistance wires",
C:"Insulation pads",
D:"Brazing"
},
answer:"A"
},

{
num:122,
question:"In DC generator, pole shoes are fastened to pole core by :",
options:{
A:"Rivet",
B:"Brazing",
C:"Welding",
D:"Counter sunk screws"
},
answer:"D"
},

{
num:123,
question:"In DC generators, current to the external circuit from the armature is given through :",
options:{
A:"Commutator",
B:"Slip rings",
C:"Solid connection",
D:"Yoke"
},
answer:"A"
},

{
num:124,
question:"The armature winding of a D.C. machine is made up of a number of coils distributed in a large number of armature slots instead of placing all the coils in two slots to",
options:{
A:"Get sinusoidal emf at the output terminals",
B:"Have minimum heat dissipation from the armature",
C:"Make the armature dynamically balanced",
D:"Get the maximum generated emf in the armature"
},
answer:"C"
},

{
num:125,
question:"A 6-pole, wave-wound armature has 600 conductor and is driven at 700 rpm. Determine the generated EMF in the armature if the flux per pole is 10 mWb.",
options:{
A:"230 V",
B:"420 V",
C:"210 V",
D:"500 V"
},
answer:"C"
},

{
num:126,
question:`Consider the following figure for a 4-pole, 3-phase, 24-slots double layer winding. Find the pole pitch and the slot pitch angle.

<div style="text-align:center;">
<img src="../Images/q126.png"
style="width:100%;max-width:500px;border:1px solid #ccc;border-radius:8px;padding:5px;background:white;display:block;margin:auto;">
</div><br>`,
options:{
A:"4 and 40 electrical degrees",
B:"5 and 50 electrical degrees",
C:"6 and 30 electrical degrees",
D:"6 and 60 electrical degrees"
},
answer:"C"
},

{
num:127,
question:"In armature winding, the distance between the segments to which the ends of coils are connected is?",
options:{
A:"commutator pitch",
B:"resultant pitch",
C:"back pitch",
D:"front pitch"
},
answer:"A"
},

{
num:128,
question:"The armature of a DC machine is placed on the rotor to ________ .",
options:{
A:"Reduce losses",
B:"Save iron",
C:"Support commutation",
D:"Decrease armature reaction"
},
answer:"C"
},

{
num:129,
question:"In a 6-pole DC machine, 90 mechanical degrees corresponds to how many electrical degrees?",
options:{
A:"270",
B:"180",
C:"30",
D:"45"
},
answer:"A"
},

{
num:130,
question:"When a single turn coil rotates in a uniform magnetic field, at uniform speed, the induced emf will be?",
options:{
A:"Alternating",
B:"Steady",
C:"Pulsating",
D:"None of these"
},
answer:"A"
},

{
num:131,
question:"The brushes in d.c. machines are made of carbon",
options:{
A:"to reduce the size of brushes",
B:"to reduce the wear and tear of commutator",
C:"to increase the efficiency of the commutator",
D:"None of these"
},
answer:"B"
},
{
num:132,
question:"The induced emf in the armature conductor of a D.C. machine is",
options:{
A:"Sinusoidal",
B:"Trapezoidal",
C:"Rectangular unidirectional",
D:"Triangular"
},
answer:"A"
},

{
num:133,
question:"In a commutator",
options:{
A:"copper is harder than mica",
B:"mica and copper are equally hard",
C:"mica is harder than copper",
D:"none of the above"
},
answer:"C"
},

{
num:134,
question:"A dc machine having a symmetrical closed-circuit armature winding and a sinusoidal air gap flux density distribution, will have a sinusoidal voltage induced in the individual coils. The resultant brush voltage will have a waveform",
options:{
A:"Sinusoidal with the negative half reversed",
B:"Unidirectional and constant without any ripples",
C:"Unidirectional and constant with ripples superimposed",
D:"Sinusoidal positive half and zero negative half, in each cycle"
},
answer:"C"
},

{
num:135,
question:"The insulating material used between the commutator segments is normally",
options:{
A:"graphite",
B:"paper",
C:"mica",
D:"insulting varnish"
},
answer:"C"
},

{
num:136,
question:"In the case of lap winding resultant pitch is",
options:{
A:"multiplication of front and back pitches",
B:"division of front pitch by back pitch",
C:"sum of from and back pitches",
D:"difference of front and back pitches"
},
answer:"D"
},

{
num:137,
question:`Match column I with column II and choose the correct answer from options given below:<br><br>

<table style="width:100%;border-collapse:collapse;">
<tr>
<td style="width:50%;vertical-align:top;">
<b>Column I</b><br>
(Type of winding conductor)<br><br>

1. Cylindrical<br>
2. Cross over<br>
3. Helical<br>
4. Continuous disk
</td>

<td style="width:50%;vertical-align:top;">
<b>Column II</b><br>
(Max current per conductor)<br><br>

a. upto 40 A<br>
b. upto 80 A<br>
c. more than 300 A<br>
d. 12 amp and more
</td>
</tr>
</table>`,

options:{
A:"1 - b, 2 - c, 3 - d, 4 - a",
B:"1 - c, 2 - d, 3 - a, 4 - b",
C:"1 - a, 2 - b, 3 - c, 4 - d",
D:"1 - b, 2 - a, 3 - c, 4 - d"
},
answer:"D"
},
    
{
num:138,
question:`Which part of the DC machine is shown in the given figure.

<div style="text-align:center;">
<img src="../Images/q138.png"
style="width:100%;max-width:500px;border:1px solid #ccc;border-radius:8px;padding:5px;background:white;display:block;margin:auto;">
</div><br>`,

options:{
A:"Yoke",
B:"Pole core",
C:"Armature",
D:"Commutator"
},
answer:"A"
},
 
{
num:139,
question:`An elementary cylindrical machine has one full-pitch coil in the stator, but the rotor may have (i) two poles or (ii) four poles of permanent magnets. The time-varying voltage that could be induced in the stator coil for one rotation of the rotor, which the rotor is revolving at a constant speed are shown in the figures A, B, C and D below:<br><br>

<div style="text-align:center;">
<img 
src="../Images/q139.png"
style="
width:100%;
max-width:500px;
border:1px solid #ccc;
border-radius:8px;
padding:5px;
background:white;
display:block;
margin:auto;
">
</div>

<br>

Select the correct combination from the code given below:`,

options:{
A:"2-Pole → A , 4-Pole → D",
B:"2-Pole → A , 4-Pole → B",
C:"2-Pole → C , 4-Pole → D",
D:"2-Pole → B , 4-Pole → C"
},

answer:"B"
},

{
num:140,
question:"For electromechanical energy conversion, a magnetic field is employed as the medium rather than electric field because",
options:{
A:"The stored energy density for practicable field strength is low in the electric field",
B:"The electric field presents insulation problem",
C:"The specific magnetic loss is more than the specific dielectric loss",
D:"None of the above"
},
answer:"A"
},

{
num:141,
question:"In electrical machines the material preferred for pole shoes of electro-magnets is",
options:{
A:"pure iron",
B:"aluminium",
C:"copper",
D:"lead"
},
answer:"A"
},

{
num:142,
question:"For a simplex lap winding, the commutator pitch is equal to",
options:{
A:"+1",
B:"±1",
C:"-1",
D:"±2"
},
answer:"B"
},

{
num:143,
question:"The number of commutator segments in a dc machine is equal to the no of",
options:{
A:"coil-sides",
B:"turns",
C:"coils",
D:"slots"
},
answer:"C"
},

{
num:144,
question:"In lap windings, the equalizer rings are used to save",
options:{
A:"armature winding from carrying circulating currents",
B:"commutator from carrying circulating currents",
C:"brushes from carrying circulating currents",
D:"armature core from eddy currents"
},
answer:"A"
},

{
num:145,
question:"The basic requirement of a d.c. armature winding is that it must be...............",
options:{
A:"A lap winding",
B:"A closed one",
C:"A wave winding",
D:"Either 'a' or 'c'"
},
answer:"B"
},

{
num:146,
question:"Electromagnetic torque in rotating electrical machinery is present when",
options:{
A:"air-gap is uniform",
B:"stator winding alone carries current",
C:"rotor winding alone carries current",
D:"both stator and rotor winding carries current"
},
answer:"D"
},

{
num:147,
question:"The output indicated on the name plate of any motor is always the",
options:{
A:"Gross power",
B:"Power drawn in kVA",
C:"Power drawn in kW",
D:"Output power to shaft"
},
answer:"D"
},

{
num:148,
question:"If the angular speed of rotation of the armature of alternating current generator is doubled, then the induced electromotive force will be-",
options:{
A:"Twice",
B:"Four times",
C:"No change",
D:"Half"
},
answer:"A"
},

{
num:149,
question:"Which one is not a valid condition for the wave winding?",
options:{
A:"Back pitch and front pitch are of the same sign",
B:"Back pitch and front pitch are odd numbers",
C:"Back pitch and front pitch may differ by two and may be equal also",
D:"Commutator pitch is always unity"
},
answer:"C"
},

{
num:150,
question:"______ may be variously defined as the periphery of the armature divided by the number of poles of the generator i.e., the distance between two adjacent poles.",
options:{
A:"Pole shoes",
B:"Pole coils",
C:"pole-pitch",
D:"Pole cores"
},
answer:"C"
},

{
num:151,
question:`Which among the following serves the two purposes i.e.,<br><br>

1. They support the exciting coils (or field coils)<br>

2. They spread out the flux in the air-gap and also reduce the reluctance of the magnetic path`,
options:{
A:"Armature core",
B:"A Yoke",
C:"Pole shoes",
D:"Commutator"
},
answer:"C"
},

{
num:152,
question:"Which among the following category of rotary motion is INCORRECT?",
options:{
A:"One coil each on stator and on rotor",
B:"Switched currents in rotor coils",
C:"Machines with permanent magnets",
D:"Machines with no rotor coil, but with permanence variation"
},
answer:"B"
},

{
num:153,
question:"Identify the checks which is NOT necessary prior to starting of a machine?",
options:{
A:"Vibration tests",
B:"Tests on cooling system",
C:"Load tests",
D:"Efficiency tests"
},
answer:"D"
},

{
num:154,
question:"In DC machine torque is proportional to ________.",
options:{
A:"flux",
B:"armature current",
C:"both flux and armature current",
D:"None of the above"
},
answer:"C"
},

{
num:155,
question:"In DC machines, the internal characteristics are plotted between:",
options:{
A:"EMF induced in the armature (E) vs field current (Iₑ)",
B:"Terminal voltage (Vₜ) vs load current (Iₗ)",
C:"Terminal voltage (Vₜ) vs armature current (Iₐ)",
D:"EMF induced in the armature (E) vs armature current (Iₐ)"
},
answer:"D"
},

{
num:156,
question:"Swinburne test is conducted on DC machine under which of the following conditions?",
options:{
A:"Half load",
B:"Full load",
C:"No load",
D:"Any of the above"
},
answer:"C"
},

{
num:157,
question:"Which of the following is one of the categories of core loss in a DC machine?",
options:{
A:"Hysteresis loss",
B:"Friction loss",
C:"Loss due to series field winding",
D:"Windage loss"
},
answer:"A"
},

{
num:158,
question:"The thickness of lamination (which reduces eddy current loss) in electrical machine varies from: (Select the closest range)",
options:{
A:"0.1 to 2 mm",
B:"0.5 to 5 mm",
C:"0.5 to 2 mm",
D:"0.1 to 1 mm"
},
answer:"B"
},

{
num:159,
question:`Consider the following statements:<br><br>

The use of interpoles in dc machines is to counteract the<br>

1. Reactance voltage<br>

2. Demagnetizing effect of armature mmf in the commutating zone<br>

3. Cross-magnetizing effect of armature mmf in the commutating zone<br><br>

Which of these statements (s) is/are correct?`,
options:{
A:"1 and 2",
B:"2 and 3",
C:"1 and 3",
D:"3 alone"
},
answer:"C"
},

{
num:160,
question:"The number of parallel paths in the armature winding of a four pole wave connected DC machine having 28 coil sides is",
options:{
A:"28",
B:"14",
C:"4",
D:"2"
},
answer:"D"
},

{
num:161,
question:"If the armature coil of a DC machine is N turns then Number of conductors of any coil side is called",
options:{
A:"2N",
B:"N/2",
C:"N²",
D:"N"
},
answer:"D"
},

{
num:162,
question:`Consider the statements given below:<br><br>

Statement A: Efficiency of a slip ring motor is less than that of a squirrel cage motor.<br>

Statement B: Slip ring achieves medium range of starting torque.<br><br>

Which statement is correct about the two statements?`,
options:{
A:"B is true but A is false.",
B:"A and B are true, but B is not the correct explanation of A.",
C:"A and B are true, and B is the correct explanation of A.",
D:"A is true but B is false."
},
answer:"D"
},

{
num:163,
question:"The most powerful electromagnet in a normal DC machine operating at full load condition is",
options:{
A:"Field winding",
B:"Armature winding",
C:"inter pole winding",
D:"Compensating winding"
},
answer:"A"
},

{
num:164,
question:"Which of the following losses is together called iron losses?",
options:{
A:"Eddy current loss and hysteresis loss",
B:"Eddy current loss and frictional loss",
C:"Hysteresis loss and copper loss",
D:"Hysteresis loss and frictional loss"
},
answer:"A"
},

{
num:165,
question:"In dc machines, the field-flux axis and armature-mmf axis are respectively along",
options:{
A:"Direct axis and indirect axis",
B:"Direct axis and inter-polar axis",
C:"Quadrature axis and direct axis",
D:"Quadrature axis and inter-polar axis"
},
answer:"B"
},

{
num:166,
question:"Under-commutation results in",
options:{
A:"Sparking at the middle of the brush",
B:"Sparking at the leading edge of the brush",
C:"Sparking at the trailing edge of the brush",
D:"No sparking"
},
answer:"C"
},

{
num:167,
question:`Assumption A : Fractional pitch winding are used in DC machine.<br><br>

Reason B : Fractional pitch winding reduces sparking on D.C. machine.`,
options:{
A:"A and B are true and B, is the correct explanation of A.",
B:"B is true, but A is false",
C:"A and B are true, but B, is not correct explanation of A",
D:"A is true and B is false"
},
answer:"A"
},

{
num:168,
question:"Which is the basic power equation of dynamo (DC machine)?",
options:{
A:"Poutput = Pinput",
B:"Pinput = Poutput − Ploss",
C:"Poutput = Pinput + Ploss",
D:"Pinput = Poutput + Ploss"
},
answer:"D"
},

{
num:169,
question:"Which of the following parts is NOT connected in a DC machine?",
options:{
A:"Armature",
B:"Damper windings",
C:"Commutator",
D:"Carbon brushes"
},
answer:"B"
},

{
num:170,
question:"Insulating material, cotton or oiled cambric tapes, are used for which part of machines?",
options:{
A:"For insulating terminals of high-voltage machines",
B:"Insulation of commutators",
C:"Taping armature and field coils of traction motor stator coils of high-voltage alternators",
D:"Rectangular conductors such as used in large D.C. machines"
},
answer:"D"
},

{
num:171,
question:"Which of the following is NOT one of the categories of copper loss in a DC machine?",
options:{
A:"Brush contact resistance loss",
B:"Armature loss",
C:"Eddy current loss",
D:"Field winding loss"
},
answer:"C"
},

{
num:172,
question:"The above figure about a push button is:",
options:{
A:"A photographic view of push-button.",
B:"A symbol of push button with 1 NO and 1 NC contact.",
C:"A multiline diagram of push button.",
D:"A push button is shown in pressed condition with its NC contact becoming open and NO contact becoming close."
},
answer:"B"
},

{
num:173,
question:"The ________ is mainly utilised for spreading the magnetic flux to avoid the field coil from falling.",
options:{
A:"pole shoe",
B:"brush",
C:"yoke",
D:"commutator"
},
answer:"A"
},

{
num:174,
question:"The direction of the magnetic lines of forces is",
options:{
A:"From north to south poles",
B:"From south to north pole",
C:"From one end of the magnet to the other",
D:"From positive to negative charges"
},
answer:"A"
},

{
num:175,
question:"In a 6-pole DC machine, 45 mechanical degrees corresponds to __________ electrical degrees.",
options:{
A:"45",
B:"180",
C:"90",
D:"135"
},
answer:"D"
},

{
num:176,
question:"Which of the following practices is an example of a medium-term energy conservation scheme?",
options:{
A:"Improved housekeeping",
B:"Minimisation of excess combustion air in furnace",
C:"Improvement and low-cost modifications in existing system",
D:"Repairs of system or leakages"
},
answer:"C"
},

{
num:177,
question:"Which one of the following statements is not correct regarding lap and wave winding?",
options:{
A:"Lap-winding is suitable for high-voltage but low-current generators.",
B:"Lap-winding is suitable for low-voltage but high-current generators.",
C:"Wave-winding is used for high-voltage, low-current machines.",
D:"When large currents are required, it is necessary to use lap-winding."
},
answer:"A"
},

{
num:178,
question:"Which one of the following statements is not correct regarding simplex lap winding of a DC machine?",
options:{
A:"The total number of brushes is equal to the number of poles.",
B:"The number of parallel paths in the armature is two.",
C:"The emf between the positive and the negative brushes is equal to the emf generated in any one of the parallel paths.",
D:"If Z is the total number of armature conductors in any parallel path is Z/P."
},
answer:"B"
},

{
num:179,
question:"An electromechanical energy conversion device has cylindrical stator but salient pole rotor. If δ is the angle between the stator field and rotor field, the average torque developed is proportional to (A and B are constants):",
options:{
A:"A sin δ",
B:"A sin 2δ",
C:"A sin δ + B sin 2δ",
D:"Zero"
},
answer:"C"
},

{
num:180,
question:"What is the instrument used to measure the gap between starter and rotor of a motor?",
options:{
A:"Ring gauge",
B:"Radius gauge",
C:"Feeler gauge",
D:"Snap gauge"
},
answer:"C"
},

{
num:181,
question:"Which is the basic requirement of electrical machine foundation?",
options:{
A:"Foundation made up of cement concrete.",
B:"Foundations should be designed considering the shocks and vibrations resulting from operation of machines.",
C:"Foundation should resist attack from chemicals in soil.",
D:"Foundation should be taken deep enough."
},
answer:"B"
}
]
});
