setWindingData({
    metaConfig: {
        title: "DC Generator (Part 1)",
        range: "Question Range: 1 to 70",
        hours: 1,
        minutes: 0
    },
    questions: [
        {num:1, question:"In a DC generator, brushes are made of", options:{A:"copper", B:"aluminium", C:"carbon or graphite", D:"laminated steel"}, answer:"C"},
        {num:2, question:"If a self-excited DC generator after being installed fails to build up on its first trial run, the first thing to do is to", options:{A:"Check armature insulation", B:"Reverse field connections", C:"Increase the speed of prime mover", D:"Increase the field resistance"}, answer:"B"},
        {num:3, question:"Generator efficiency is maximum when:", options:{A:"Variable loss is minimum", B:"Constant loss = Variable loss", C:"Constant loss is minimum", D:"Constant loss is half of the variable loss"}, answer:"B"},
        {num:4, question:"In DC armature winding, wave winding has parallel paths.", options:{A:"Many", B:"Three", C:"Four", D:"Two"}, answer:"D"},
        {num:5, question:"The use of compensating winding in a D.C. generator is to:", options:{A:"Neutralize m.m.f.", B:"Neutralize cross m.m.f.", C:"Maintain uniform flux distribution", D:"Compensate for decrease in main flux"}, answer:"B"},
        {num:6, question:"The emf induced in a conductor rotating in a bipolar field is", options:{A:"AC", B:"DC", C:"AC & DC both", D:"None of these"}, answer:"A"},
        {num:7, question:"The wave form of the armature m.m.f. in DC machine is...............", options:{A:"square", B:"rectangular", C:"triangular", D:"sinusoidal"}, answer:"C"},
        {num:8, question:"In DC machine shape of main field flux distribution is", options:{A:"triangular", B:"flat tapped or trapezoidal", C:"saddle shape", D:"peaky in nature"}, answer:"B"},
        {num:9, question:"The principle of dynamically induced emf is utilised in :", options:{A:"Choke", B:"Transformer", C:"Thermocouple", D:"Generator"}, answer:"D"},
        {num:10, question:"Dummy coils are used for", options:{A:"increasing efficiency", B:"reducing armature reaction", C:"mechanical balancing", D:"all options are correct"}, answer:"C"},
        {num:11, question:"For a linear electromagnetic circuit, which of the following statement is true?", options:{A:"Field energy is equal to the co-energy", B:"Field energy is greater than the co-energy", C:"Field energy is lesser than the co-energy", D:"Co-energy is zero"}, answer:"A"},
        {num:12, question:"In electrical machines, magnetic leakage is undesirable. This is due to the fact that it– 1. Lowers the power efficiency 2. Produces fringing 3. Leads to increased weight", options:{A:"Only 1", B:"1, 2 and 3", C:"Only 2", D:"Both 2 and 3"}, answer:"D"},
        {num:13, question:"If a machine has P poles and the armature rotates at N revolutions per minute, then the frequency of induced emf in the armature winding of the machine is:", options:{A:"f = 50/PN Hz", B:"f = 120/PN Hz", C:"f = PN/120 Hz", D:"f = PN/50 Hz"}, answer:"C"},
        {num:14, question:"_____ helps to find out the direction of current in the conductor of a generator.", options:{A:"Cork screw rule", B:"Right hand thumb rule", C:"Fleming left hand rule", D:"Fleming right hand rule"}, answer:"D"},
        {num:15, question:"Lap winding is preferred for which type of machines?", options:{A:"Low current & low voltage", B:"High current & high voltage", C:"High current and low voltage", D:"Low current & high voltage"}, answer:"C"},
        {num:16, question:"A dynamo is sometimes said to generate electricity. It is actually acts as a source of:", options:{A:"charge", B:"magnetism", C:"emf", D:"energy"}, answer:"C"},
        {num:17, question:"The alternating voltage generated in the DC generator can be converted into direct voltage by a device called _______.", options:{A:"varactor", B:"commutator", C:"armature", D:"pole pitch"}, answer:"B"},
        {num:18, question:"Reactance voltage of a DC machine is ______ times of commutation.", options:{A:"Inversely proportional to", B:"Directly proportional to", C:"Independent of", D:"Equal to"}, answer:"A"},
        {num:19, question:"Which of the following windings is connected in series with armature winding of DC machine?", options:{A:"Auxiliary winding", B:"Compensating winding", C:"Commutating Pole winding", D:"Both (b) and (c)"}, answer:"D"},
        {num:20, question:"In a D.C. machine, on no load the magnetic neutral axis", options:{A:"Moves from geometrical neutral axis in the direction of rotation", B:"Moves from geometrical neutral axis in the opposite direction of rotation", C:"Coincides with the geometrical neutral axis", D:"None of the above"}, answer:"C"},
        {num:21, question:"In a DC generator, whenever the rotating armature coil is parallel to the lines of flux:", options:{A:"the rate of change of flux linkage is minimum", B:"the flux linked with the coil is minimum and rate of change of flux linkage is maximum", C:"the flux linked with the coil is maximum", D:"the flux linked with the coil is maximum and rate of change of flux linkage is minimum"}, answer:"B"},
        {num:22, question:"The line representing the critical resistance of a dc generator _______ its characteristics (OCC).", options:{A:"intersects", B:"does not intersect", C:"just touches", D:"runs parallel to"}, answer:"C"},
        {num:23, question:"Compensating winding in a DC machine is placed", options:{A:"On Yoke in the interpolar gap", B:"On Yoke in the pole faces", C:"On partly in armature slots and partly in pole faces", D:"In armature slots"}, answer:"B"},
        {num:24, question:"In a symmetrical rotating machine, the impedances met by armature currents of a given sequence are:", options:{A:"opposite in two phases and zero in remaining", B:"equal in the three phases", C:"zero in two phases", D:"different in the three phases"}, answer:"B"},
        {num:25, question:"The function of pole-shoes in a DC machine is:", options:{A:"to increase field winding reactance", B:"to decrease field winding resistance", C:"to increase field winding resistance", D:"uniform distribution of flux"}, answer:"D"},
        {num:26, question:"In a 4-pole dc machine, a coil span of 120 electrical degrees is equal to:", options:{A:"240 mechanical degrees", B:"60 mechanical degrees", C:"180 mechanical degrees", D:"120 mechanical degrees"}, answer:"B"},
        {num:27, question:"The yoke in a large DC machine is made of:", options:{A:"Grain oriented steel", B:"Cast iron", C:"Cast steel", D:"Mild steel"}, answer:"C"},
        {num:28, question:"The relative speed between the magnetic fields of stator and rotor under steady state operation is zero for a:", options:{A:"DC machine", B:"3-phase induction machine", C:"Synchronous machine", D:"All of these"}, answer:"D"},
        {num:29, question:"A device which converts electrical energy into mechanical energy is termed as:", options:{A:"Capacitor", B:"Generator", C:"Motor", D:"Converter"}, answer:"C"},
        {num:30, question:"In differential compound DC machine magnetic field produced by shunt and series field act in______ direction.", options:{A:"Same", B:"Opposite", C:"Vertical", D:"Horizontal"}, answer:"B"},
        {num:31, question:"The Pitch of wave winding is:", options:{A:"YB − YF", B:"YB", C:"YB + YF", D:"YF"}, answer:"C"},
        {num:32, question:"The distance between two consecutive and similar top coil side is called", options:{A:"Back pitch", B:"Front pitch", C:"Winding pitch", D:"Commutator pitch"}, answer:"C"},
        {num:33, question:"Which part of a DC motor has the maximum flux", options:{A:"Pole core", B:"Interpole", C:"Leading pole tip", D:"Trailing pole tip"}, answer:"C"},
        {num:34, question:"Brushes of D.C. machines are made of-", options:{A:"carbon", B:"soft copper", C:"hard copper", D:"all of these"}, answer:"A"},
        {num:35, question:"Which of the followings are true with respect of interpoles in dc machine? 1. Reduce armature reaction effect in interpolar region. 2. Windings are connected in series with armature. 3. Have the same dimensions as main poles.", options:{A:"1 and 2", B:"2 and 3", C:"1 and 3", D:"1, 2 and 3"}, answer:"A"},
        {num:36, question:"Pole shoe of a dc machine is laminated for the purpose of", options:{A:"Decreasing hysteresis loss", B:"Decreasing eddy current loss", C:"Manufacturing ease", D:"Decreasing both hysteresis & eddy current loss"}, answer:"B"},
        {num:37, question:"Which of the following is true with a commutator?", options:{A:"It acts as an inverter in a motor", B:"It acts as rectifier in a generator", C:"It requires frequent maintenance", D:"all the above"}, answer:"D"},
        {num:38, question:"The resistance of armature winding depends on", options:{A:"length of conductor", B:"cross sectional area of the conductor", C:"number of conductors", D:"all of the above"}, answer:"D"},
        {num:39, question:"Which law describes the dynamically induced EMF in a generator?", options:{A:"Ohm's law", B:"Biot Savart's law", C:"Kirchhoff's law", D:"Faraday's law"}, answer:"D"},
        {num:40, question:"______ represents the electrical energy converted into mechanical energy by a dc motor.", options:{A:"EbIa", B:"VIa", C:"EgIa", D:"VIsh"}, answer:"A"},
        {num:41, question:"For a P pole machine, the relation between electrical and mechanical degrees is", options:{A:"θelec. = (2/P) θmech.", B:"θelec. = (4/P) θmech.", C:"θelec. = Pθmech.", D:"θelec. = (P/2) θmech."}, answer:"D"},
        {num:42, question:"Two dc machines A and B have armature circuit resistances of the order of 0.4 ohm and 1.2 ohm respectively. Which machine is bigger than the other for same voltage rating?", options:{A:"A is bigger than B", B:"B is bigger than A", C:"Both have same size", D:"Field circuit resistance will decide the size of machine"}, answer:"A"},
        {num:43, question:"What are slot wedges in a dc machine, made of?", options:{A:"Mild steel", B:"Silicon steel", C:"Fibre", D:"Cast iron"}, answer:"C"},
        {num:44, question:"The working of a dynamo is based on the principle of -", options:{A:"Electromagnetic induction", B:"Conversion of energy into electricity", C:"Magnetic effects of current", D:"Heating effects of current"}, answer:"A"},
        {num:45, question:"The output of a dynamo using a splitting commutator is-", options:{A:"D.C.", B:"A.C.", C:"Fluctuating D.C.", D:"Half-wave rectified voltage"}, answer:"C"},
        {num:46,question:"The inter poles in DC machines have a tapering shape in order to",options:{A:"reduce the overall weight",B:"reduce the saturation in the inter pole",C:"economies on the material required for inter poles",D:"increase the acceleration of commutation"},answer:"B"},
        {num:47,question:"EMF induced in a coil rotating in a uniform Magnetic field will be maximum when the:",options:{A:"Rate of change of flux linkage is minimum",B:"Rate of change of flux linkage is maximum",C:"Rate of cutting flux by the coil sides is minimum",D:"Flux linking with the coil is maximum"},answer:"B"},
        {num:48,question:"Force on a Conductors is :",options:{A:"unidirectional",B:"bidirectional",C:"Either of these",D:"none of these"},answer:"A"},
        {num:49,question:"Electro–mechanical voltage regulators generally find applications in :",options:{A:"generators",B:"transformers",C:"reactors",D:"all option are correct"},answer:"A"},
        {num:50,question:"In which of the following voltage sources, the movement of conductors in a magnetic field is used to produce voltage?",options:{A:"in a thermo couple",B:"in a zinc copper element",C:"in a DC generator",D:"in a transformer"},answer:"C"},
        {num:51,question:"What is called the electro-motive force(e.m.f) of a voltage source?",options:{A:"Terminal voltage when load is applied",B:"Internal voltage when no load is applied",C:"Product of internal resistance and load current",D:"Electric pressure provided to the load"},answer:"B"},
        {num:52,question:"In DC motor, where does iron loss occur?",options:{A:"the yoke",B:"the armature",C:"the field",D:"None of these"},answer:"B"},
        {num:53,question:"Consider the following parts of a dc machine: 1. Yoke 2. Armature core 3. Brushes 4. Pole core Which of the above parts are subjected to iron loss?",options:{A:"1 and 2 only",B:"2 only",C:"1 only",D:"1, 2, 3 and 4"},answer:"B"},
        {num:54,question:"The e.m.f. of a DC generator depends on............",options:{A:"commutation",B:"speed",C:"frequency",D:"brush contact drop"},answer:"B"},
        {num:55,question:"How many segments will be there for the commutator of a 6 pole d.c. machine having a simple wave wound armature with 72 slots?",options:{A:"73",B:"72",C:"71",D:"70"},answer:"B"},
        {num:56,question:"The parts of the armature electric circuit which take active part in e.m.f. generation are..............",options:{A:"The coil sides inside the slots",B:"The overhangs",C:"both the coil sides inside the slots and the overhangs",D:"the commutator segments"},answer:"A"},
        {num:57,question:"The commutator in a D.C. machine acts as",options:{A:"a mechanical inverter",B:"a mechanical rectifier",C:"current controller",D:"either (a) or (b)"},answer:"D"},
        {num:58,question:"For a 6-pole D.C. machine with wave wound armature, the number of brushes required is",options:{A:"2",B:"4",C:"6",D:"12"},answer:"A"},
        {num:59,question:"A triangular mmf wave is produced in the air-gap of an electric machine. Such a wave is produced by",options:{A:"Stator of an induction machine",B:"Rotor of a synchronous machine",C:"Stator of a dc machine",D:"Rotor of a dc machine"},answer:"D"},
        {num:60,question:"Function of interpoles in a D.C. machine is to",options:{A:"reduce field winding heating.",B:"improve commutation.",C:"compensate for air-gap variation",D:"reduce losses"},answer:"B"},
        {num:61,question:"The commutator segments of D.C. machine are made of",options:{A:"tungsten",B:"hard-drawn copper",C:"soft copper",D:"electrolytic copper"},answer:"B"},
        {num:62,question:"Which of the following expression satisfies the Faraday's law of electromagnetic induction?",options:{A:"e = -N * (dϕ/dt)",B:"e = N * (dϕ/dt)",C:"e = -N ∫ dϕdt",D:"e = (N * d²ϕ) / dt²"},answer:"A"},
        {num:63,question:"The function of the commutator in a DC machine is.................",options:{A:"to change alternating current into direct current",B:"to improve commutation",C:"for easy speed control",D:"to change alternating voltage to direct voltage"},answer:"D"},
        {num:64,question:"A time-varying flux causes an induced electromotive force. What law does this statement represent?",options:{A:"Ampere's law",B:"Faraday's law",C:"Lenz's law",D:"Field form of Ohm's law"},answer:"B"},
        {num:65,question:"The number of brushes required for a 4 pole, lap wound DC machine is…………?",options:{A:"8",B:"1",C:"4",D:"2"},answer:"C"},
        {num:66,question:"In dc machine iron losses cause",options:{A:"heating in core",B:"less in efficiency",C:"rise in temperature of ventilating air",D:"all of the mentioned"},answer:"D"},
        {num:67,question:"The field winding will be drawn at what degree?",options:{A:"60 degree",B:"30 degree",C:"90 degree",D:"180 degree"},answer:"C"},
        {num:68,question:"Compensating winding is placed in the",options:{A:"pole shoe",B:"armature core",C:"main field",D:"all option are correct"},answer:"A"},
        {num:69,question:"DC machine winding are",options:{A:"full pitched",B:"short pitched",C:"either of these",D:"none of these"},answer:"A"},
        {num:70,question:"The armature winding is connected to the external power source through a",options:{A:"commutator system",B:"brush system",C:"commutator brush system",D:"none of these"},answer:"C"}
    ]
});
